---
- name: check display does not sleep
  win_command: >
      powercfg /q 381b4222-f694-41f0-9685-ff5bb260df2e
      7516b95f-f776-4464-8c53-06167f40cc99
      3c0bc021-c8a8-4e07-a973-6b14cbcb2b7e
  register: display
  changed_when: false

- win_command: >
      powercfg /SETACVALUEINDEX 381b4222-f694-41f0-9685-ff5bb260df2e
      7516b95f-f776-4464-8c53-06167f40cc99
      3c0bc021-c8a8-4e07-a973-6b14cbcb2b7e 0
  when: "display.stdout.find('Current AC Power Setting Index: 0x00000000') == -1"

- name: Ensure windows defender is disabled
  win_shell: Get-WindowsFeature Windows-Defender
  register: defender
  changed_when: false

- win_feature:
      name: Windows-Defender
      state: absent
  register: defender
  when: defender.stdout.find("Installed") != -1

- win_reboot:
  when: defender.changed
